version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: cinemais
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    depends_on:
      - db
    volumes:
      - .:/app   
      - /app/node_modules
    ports:
      - "3000:3000"
    env_file:
      - .env
    command: npm run start:dev
    networks:
      - backend

volumes:
  db_data:

networks:
  backend:
